GET  http://localhost:8080/
Content-Type: application/json
################################
POST  http://localhost:8080/predict-conversation
Content-Type: application/json

{
    "conversations": [{ "user": ["asdassadasdasd","asdasdads"],"expert":["asdasd","asdasd"]},{ "user": ["asdasd","asdasdads"],"expert":["asdasd","asdasd"]},{ "user": ["asdasd","asdasdads"],"expert":["asdasd","asdasd"]}]
}
#######################
GET https://chatbot-capstone1.herokuapp.com/train
Content-Type: application/json
################################
POST http://192.168.5.211:8080/
Content-Type: application/json

{
    "question": "quên mật khẩu"
}